// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NeueVox.Model.NeuevoxModel.Context;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace NeueVox.Model.Migrations
{
    [DbContext(typeof(NeueVoxContext))]
    [Migration("20260315021639_addingAuthentification")]
    partial class addingAuthentification
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("NeueVox.Model.NeuevoxModel.Class", b =>
                {
                    b.Property<Guid>("ClassId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ClassNumber")
                        .HasColumnType("text");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProfessorId")
                        .HasColumnType("uuid");

                    b.Property<string>("Semester")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ClassId");

                    b.HasIndex("CourseId");

                    b.HasIndex("ProfessorId");

                    b.ToTable("Classes");
                });

            modelBuilder.Entity("NeueVox.Model.NeuevoxModel.Course", b =>
                {
                    b.Property<Guid>("CourseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CourseCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CourseTitle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("CourseId");

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("NeueVox.Model.NeuevoxModel.Document", b =>
                {
                    b.Property<Guid>("DocumentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClassId")
                        .HasColumnType("uuid");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FileType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FileUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("DocumentId");

                    b.HasIndex("ClassId");

                    b.ToTable("Documents");
                });

            modelBuilder.Entity("NeueVox.Model.NeuevoxModel.Evaluation", b =>
                {
                    b.Property<Guid>("EvaluationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClassId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EvaluationTitle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("MaxScore")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Weight")
                        .HasColumnType("numeric");

                    b.HasKey("EvaluationId");

                    b.HasIndex("ClassId");

                    b.ToTable("Evaluations");
                });

            modelBuilder.Entity("NeueVox.Model.NeuevoxModel.Grade", b =>
                {
                    b.Property<Guid>("GradeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("EvaluationId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Score")
                        .HasColumnType("numeric");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid");

                    b.HasKey("GradeId");

                    b.HasIndex("EvaluationId");

                    b.HasIndex("StudentId");

                    b.ToTable("Grades");
                });

            modelBuilder.Entity("NeueVox.Model.NeuevoxModel.Program", b =>
                {
                    b.Property<Guid>("ProgramId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ProgramCode")
                        .HasColumnType("integer");

                    b.Property<string>("ProgramName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ProgramId");

                    b.ToTable("Programs");
                });

            modelBuilder.Entity("NeueVox.Model.NeuevoxModel.StudentClass", b =>
                {
                    b.Property<Guid>("StudentClassId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClassId")
                        .HasColumnType("uuid");

                    b.Property<int>("ClassStatus")
                        .HasColumnType("integer");

                    b.Property<decimal?>("FinalGrade")
                        .HasColumnType("numeric");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid");

                    b.HasKey("StudentClassId");

                    b.HasIndex("ClassId");

                    b.HasIndex("StudentId");

                    b.ToTable("StudentClasses");
                });

            modelBuilder.Entity("NeueVox.Model.NeuevoxModel.StudentSubmission", b =>
                {
                    b.Property<Guid>("SubmissionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("EvaluationId")
                        .HasColumnType("uuid");

                    b.Property<string>("FileUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("SubmissionDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("SubmissionId");

                    b.HasIndex("EvaluationId");

                    b.HasIndex("StudentId");

                    b.ToTable("StudentSubmissions");
                });

            modelBuilder.Entity("NeueVox.Model.NeuevoxModel.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("text");

                    b.Property<DateTime?>("RefreshTokenExpiryTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SchoolEmail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("UserId");

                    b.ToTable("Users");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("NeueVox.Model.NeuevoxModel.Professor", b =>
                {
                    b.HasBaseType("NeueVox.Model.NeuevoxModel.User");

                    b.Property<string>("Departement")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("HireDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OfficeNumber")
                        .HasColumnType("text");

                    b.ToTable("Professors", (string)null);
                });

            modelBuilder.Entity("NeueVox.Model.NeuevoxModel.Student", b =>
                {
                    b.HasBaseType("NeueVox.Model.NeuevoxModel.User");

                    b.Property<DateTime>("AdmissionDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ProgramId")
                        .HasColumnType("uuid");

                    b.HasIndex("ProgramId");

                    b.ToTable("Students", (string)null);
                });

            modelBuilder.Entity("NeueVox.Model.NeuevoxModel.Class", b =>
                {
                    b.HasOne("NeueVox.Model.NeuevoxModel.Course", "Course")
                        .WithMany("Classes")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NeueVox.Model.NeuevoxModel.Professor", "Professor")
                        .WithMany("Classes")
                        .HasForeignKey("ProfessorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Professor");
                });

            modelBuilder.Entity("NeueVox.Model.NeuevoxModel.Document", b =>
                {
                    b.HasOne("NeueVox.Model.NeuevoxModel.Class", "Class")
                        .WithMany("Documents")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Class");
                });

            modelBuilder.Entity("NeueVox.Model.NeuevoxModel.Evaluation", b =>
                {
                    b.HasOne("NeueVox.Model.NeuevoxModel.Class", "Class")
                        .WithMany("Evaluations")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Class");
                });

            modelBuilder.Entity("NeueVox.Model.NeuevoxModel.Grade", b =>
                {
                    b.HasOne("NeueVox.Model.NeuevoxModel.Evaluation", "Evaluation")
                        .WithMany("Grades")
                        .HasForeignKey("EvaluationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NeueVox.Model.NeuevoxModel.Student", "Student")
                        .WithMany("Grades")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Evaluation");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("NeueVox.Model.NeuevoxModel.StudentClass", b =>
                {
                    b.HasOne("NeueVox.Model.NeuevoxModel.Class", "Class")
                        .WithMany("StudentClasses")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NeueVox.Model.NeuevoxModel.Student", "Student")
                        .WithMany("StudentClasses")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Class");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("NeueVox.Model.NeuevoxModel.StudentSubmission", b =>
                {
                    b.HasOne("NeueVox.Model.NeuevoxModel.Evaluation", "Evaluation")
                        .WithMany("StudentSubmissions")
                        .HasForeignKey("EvaluationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NeueVox.Model.NeuevoxModel.Student", "Student")
                        .WithMany("StudentSubmissions")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Evaluation");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("NeueVox.Model.NeuevoxModel.Professor", b =>
                {
                    b.HasOne("NeueVox.Model.NeuevoxModel.User", null)
                        .WithOne()
                        .HasForeignKey("NeueVox.Model.NeuevoxModel.Professor", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("NeueVox.Model.NeuevoxModel.Student", b =>
                {
                    b.HasOne("NeueVox.Model.NeuevoxModel.Program", "Program")
                        .WithMany("Students")
                        .HasForeignKey("ProgramId");

                    b.HasOne("NeueVox.Model.NeuevoxModel.User", null)
                        .WithOne()
                        .HasForeignKey("NeueVox.Model.NeuevoxModel.Student", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Program");
                });

            modelBuilder.Entity("NeueVox.Model.NeuevoxModel.Class", b =>
                {
                    b.Navigation("Documents");

                    b.Navigation("Evaluations");

                    b.Navigation("StudentClasses");
                });

            modelBuilder.Entity("NeueVox.Model.NeuevoxModel.Course", b =>
                {
                    b.Navigation("Classes");
                });

            modelBuilder.Entity("NeueVox.Model.NeuevoxModel.Evaluation", b =>
                {
                    b.Navigation("Grades");

                    b.Navigation("StudentSubmissions");
                });

            modelBuilder.Entity("NeueVox.Model.NeuevoxModel.Program", b =>
                {
                    b.Navigation("Students");
                });

            modelBuilder.Entity("NeueVox.Model.NeuevoxModel.Professor", b =>
                {
                    b.Navigation("Classes");
                });

            modelBuilder.Entity("NeueVox.Model.NeuevoxModel.Student", b =>
                {
                    b.Navigation("Grades");

                    b.Navigation("StudentClasses");

                    b.Navigation("StudentSubmissions");
                });
#pragma warning restore 612, 618
        }
    }
}
